from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "SystemAIYugioh" / "data"
TRAINING_RUNS_DIR = DATA_DIR / "training_runs"
DECK_PROFILES_DIR = DATA_DIR / "deck_profiles"

DEFAULT_SIMULATION_RUNS = 100
DEFAULT_TRAINING_RUNS = 2
MONTE_CARLO_DEFAULT_RUNS = 1000
MONTE_CARLO_SMOKE_RUNS = 80

VALIDATOR_TIMEOUT_SECONDS = 900
VALIDATOR_MATRIX_TIMEOUT_SECONDS = 2400

MATRIX_SMOKE_RUNS_PER_CELL = 1
MATRIX_FULL_RUNS_PER_CELL = 5
MATRIX_SMOKE_ENGINE_LIMIT = 4
MATRIX_SMOKE_MATCHUP_LIMIT = 4
MATRIX_SMOKE_SIDE_CANDIDATES = 4
MATRIX_FULL_SIDE_CANDIDATES = 6
MATRIX_MAX_FAILURE_RATE = 0.25
MATRIX_CACHE_MAX_AGE_SECONDS = 60 * 60 * 24 * 14
MATRIX_CACHE_MAX_ENTRIES = 5000
POST_SIDE_SMOKE_MAX_CANDIDATES = 8
POST_SIDE_FULL_MAX_CANDIDATES = 50

REGRESSION_MAX_SCORE_DROP = 8.0
REGRESSION_MAX_BRICK_INCREASE = 0.10
REGRESSION_MIN_POST_SIDE_DELTA = -8.0
REGRESSION_MIN_VALID_CANDIDATE_RATE = 0.2

LEARNING_WEIGHT_CAP = 5.0
ENGINE_WEIGHT_CAP = 5.0
SIDE_MEMORY_WEIGHT_CAP = 5.0

REPORT_VERSION = "stabilization-a-v1"
CACHE_VERSION = REPORT_VERSION
CACHE_DIR = DATA_DIR / "runtime_cache"
MATRIX_CACHE_DIR = CACHE_DIR / "matchup_matrix"

REPORT_PATHS = {
    "training": TRAINING_RUNS_DIR,
    "evaluation": TRAINING_RUNS_DIR / "evaluations",
    "matchup_matrix": TRAINING_RUNS_DIR / "matchup_matrix",
    "post_side": TRAINING_RUNS_DIR / "post_side",
    "opponent_analysis": TRAINING_RUNS_DIR / "opponent_profiles",
}
